"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React, { useState, useEffect } from "react";
import Loading from "./component/loading";
import Header from "./component/header";
import Footer from "./component/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>)

// {
//   return (

//     <html lang="en">
//       <head>
//         <meta name="description" content="Mô tả ngắn về nội dung trang (dưới 160 ký tự)" />
//         <meta name="keywords" content="Next.js, SEO, React, thẻ meta" />
//         <meta name="author" content="Tên của bạn hoặc công ty" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <Header />
//         <div >{children} </div>
//         <Footer />
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      <head>
        <title>Đăng Ký 4G Viettel - Cách Đăng Ký Gói Cước 4G Nhanh Chóng</title>
        <link rel="icon" href="/assets/img/favicon.svg" sizes="32x16" />
        <meta name="application-name" content="Viettel" />
        <meta
          name="description"
          content="Mô tả ngắn về nội dung trang (dưới 160 ký tự)"
        />
        <meta name="keywords" content="Next.js, SEO, React, thẻ meta" />
        <meta name="author" content="Tên của bạn hoặc công ty" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {loading && <Loading />}
        <Header />
        <div className="transparent-background">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
